# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcelisting', '0005_auto_20170829_0429'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribers', '0028_auto_20170829_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('published_date', models.DateField()),
                ('body_text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_client', to='subscribers.Company')),
                ('company', models.ManyToManyField(related_name='stories_company', to='subscribers.Company')),
                ('created_by', models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='stories_created_by', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_source', to='sourcelisting.Source')),
                ('updated_by', models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='story_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
