# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
