# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20170829_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='published_date',
            field=models.DateField(),
        ),
    ]
