# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20170829_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='published_date',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='story',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='story',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcelisting.Source'),
        ),
    ]
