# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcelisting', '0006_auto_20170830_0446'),
        ('stories', '0005_auto_20170830_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set([('url', 'source')]),
        ),
    ]
