# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20170912_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
