# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Author1',
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog1',
        ),
        migrations.RenameModel(
            old_name='Entry',
            new_name='Entry1',
        ),
    ]
