# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_author2_blog2_entry2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry2',
            name='authors',
            field=models.ManyToManyField(to='polls.Author2'),
        ),
        migrations.AlterField(
            model_name='entry2',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Blog2'),
        ),
    ]
