# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171206_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry2',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Blog2'),
        ),
    ]
