# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='add_source_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='add_source_updated', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_source_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
