# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcelisting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsource',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='addsource',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='addsource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_source_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addsource',
            name='updated_by',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='add_source_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
