# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcelisting', '0002_auto_20170824_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addsource',
            unique_together=set([('url', 'created_by')]),
        ),
    ]
