# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcelisting', '0003_auto_20170825_0245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSource',
            new_name='Source',
        ),
    ]
