# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0027_remove_subscriber_gender'),
        ('sourcelisting', '0004_auto_20170828_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='companies',
            field=models.ManyToManyField(related_name='source_companies', to='subscribers.Company'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='updated_by',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='source_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
