# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcelisting', '0005_auto_20170829_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='source',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='source',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='companies',
            field=models.ManyToManyField(to='subscribers.Company'),
        ),
    ]
