# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='client_name',
        ),
        migrations.AddField(
            model_name='company',
            name='company_url',
            field=models.URLField(default='umesh pandey', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_by',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Sign_Up',
        ),
    ]
