# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20170816_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_url',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
    ]
