# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_auto_20170818_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_url',
            new_name='url',
        ),
    ]
