# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_auto_20170818_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Subscriber',
        ),
    ]
