# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_auto_20170819_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
