# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribers', '0015_auto_20170819_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
