# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0019_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_by',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='updated_by',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
