# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0020_auto_20170823_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='hobbies',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
