# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0021_subscriber_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='hobbies',
        ),
    ]
