# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 05:00
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0022_remove_subscriber_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=9, null=True),
        ),
    ]
