# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0023_subscriber_my_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='my_field2',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hobbies',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
