# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0024_auto_20170824_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='gender',
            field=models.TextField(max_length=8, null=True),
        ),
    ]
