# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0025_auto_20170824_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
