# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0026_auto_20170828_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='gender',
        ),
    ]
