# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0027_remove_subscriber_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
